"""empty message

Revision ID: 296d76e89a8e
Revises: bde5e5565d17
Create Date: 2017-12-16 20:05:35.553823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296d76e89a8e'
down_revision = 'bde5e5565d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetup_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetup_polygon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetup_polygon')
    op.drop_table('meetup_line')
    # ### end Alembic commands ###
