"""empty message

Revision ID: bde5e5565d17
Revises: 
Create Date: 2017-12-16 20:04:49.219313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde5e5565d17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetup_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetup_point')
    # ### end Alembic commands ###
